name: Sync to GitLab

on:
  push:
    branches:
      - main  # Ou o nome da branch que você deseja sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add GitLab remote
      run: |
        git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.com/seu-usuario/seu-repositorio.git

    - name: Push to GitLab
      run: |
        git push gitlab HEAD:main --force  # Ou o nome da branch que você deseja sincronizar
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
